package com.ftne.topquotebot.service

import com.ftne.topquotebot.repository.Quote
import com.ftne.topquotebot.repository.QuoteDao
import com.ftne.topquotebot.repository.User
import com.ftne.topquotebot.repository.UserDao
import org.springframework.stereotype.Service
import java.time.Instant

@Service
class QuoteService(
    private val userDao: UserDao,
    private val quoteDao: QuoteDao
) {

    fun addQuote(chatId: Long, text: String): Quote {
        val user = userDao.findById(chatId) ?: run {
            val newUser = User(chatId, null, null, null)
            userDao.create(newUser)
            newUser
        }

        val quote = Quote(
            id = 0, // generated by DB
            text = text,
            timestamp = Instant.now(),
            userChatId = chatId
        )

        return quote
    }

    fun deleteQuote(chatId: Long, quoteId: Long): Boolean {
        return quoteDao.delete(quoteId, chatId)
    }

    fun getRandomQuote(chatId: Long): Quote? {
        return quoteDao.findRandomByUser(chatId)
    }

    fun getAllUserQuotes(chatId: Long): List<Quote> {
        return quoteDao.findAllByUser(chatId)
    }
}